### ISSUE TITLE
Dependency

### ISSUE THREAD

**Issue by chameleon-tbn** [goldilocks25/LiveStreamRadioMod#1]
Hello, do this mod need Extended Radio as a dependency or do it work without? If it need this mod as dependency, it would be good adding this in PDXMods.

I write here, as you have comments deactivated on PDXMods

**Comment by goldilocks25** [comment]
This mode does not require Extended radio.
Initially, there were dependencies, but now they have been removed due to significant differences in playback methods.

**Comment by chameleon-tbn** [comment]
But they Not conflict with each other either, or?

**Comment by goldilocks25** [comment]
Compatibility issues with Extended Radio have been confirmed to be non-existent. We would appreciate it if you could provide detailed information about the issue. Thank you.

**Comment by chameleon-tbn** [comment]
Good to know, that there are No conflicts. I'll maintain this information in Skyve's Compatibility Data.

**Comment by goldilocks25** [comment]
Thank you. I'll close the issue.
